services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_HOST
        value: n8n-novolabs.onrender.com
      - key: N8N_PORT
        value: 5678
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: manuel
      - key: N8N_BASIC_AUTH_PASSWORD
        value: Qwer321!
      - key: WEBHOOK_URL
        value: https://n8n-novolabs.onrender.com